// Code generated by MockGen. DO NOT EDIT.
// Source: create_aliens.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	model "github.com/d6o/alieninvasion/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockcityRandomizer is a mock of cityRandomizer interface.
type MockcityRandomizer struct {
	ctrl     *gomock.Controller
	recorder *MockcityRandomizerMockRecorder
}

// MockcityRandomizerMockRecorder is the mock recorder for MockcityRandomizer.
type MockcityRandomizerMockRecorder struct {
	mock *MockcityRandomizer
}

// NewMockcityRandomizer creates a new mock instance.
func NewMockcityRandomizer(ctrl *gomock.Controller) *MockcityRandomizer {
	mock := &MockcityRandomizer{ctrl: ctrl}
	mock.recorder = &MockcityRandomizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcityRandomizer) EXPECT() *MockcityRandomizerMockRecorder {
	return m.recorder
}

// RandomCity mocks base method.
func (m *MockcityRandomizer) RandomCity() (*model.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomCity")
	ret0, _ := ret[0].(*model.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RandomCity indicates an expected call of RandomCity.
func (mr *MockcityRandomizerMockRecorder) RandomCity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomCity", reflect.TypeOf((*MockcityRandomizer)(nil).RandomCity))
}
